version = 1

[module]
type = "android-app"
name = "app"
languageLevel = "JAVA_8"
output = "build/classes"

[sourceSets.debug]
scope = "IMPLEMENTATION"
assets = ["src/debug/assets"]
java = ["src/debug/java", "src/debug/kotlin"]
res = ["src/debug/res"]

[sourceSets.main]
scope = "IMPLEMENTATION"
assets = ["src/main/assets"]
java = ["src/main/java", "src/main/kotlin"]
res = ["src/main/res"]

[sourceSets.release]
scope = "IMPLEMENTATION"
assets = ["src/release/assets"]
java = ["src/release/java", "src/release/kotlin"]
res = ["src/release/res"]

[dependencies]
implementation = ["kotlin-stdlib"]

[android]
namespace = "com.example.speaktoflowerv5"
compileSdk = 34
minSdk = 26
targetSdk = 34
manifest = "src/main/AndroidManifest.xml"
versionCode = 1
versionName = "1.0"
isApplication = true
buildTypes = [{ name = "debug", debuggable = true, minifyEnabled = false, shrinkResources = false }, { name = "release", debuggable = false, minifyEnabled = false, shrinkResources = false, proguardFiles = ["proguard-android-optimize.txt", "proguard-rules.pro"] }]
